// HTTP Request using REST client vscode extension
// Compose MULTIPLE requests in a single file (separated by ### delimiter)
// NOTE: Single line space below content type is mandatory

### Auth Routes
### Create new user sign up
POST http://localhost:3000/reports
Content-Type: application/json

{
  "price": 4500,
  "make": "nissan",
  "model": "micra",
  "year": 2000,
  "mileage": 40000,
  "long": 0,
  "lat": 0
}

