// HTTP Request using REST client vscode extension
// Compose MULTIPLE requests in a single file (separated by ### delimiter)
// NOTE: Single line space below content type is mandatory

### Reports Routes
### Create new report
POST http://localhost:3000/reports
Content-Type: application/json

{
  "price": 14500,
  "make": "nissan",
  "model": "rouge",
  "year": 2016,
  "mileage": 60000,
  "long": 0,
  "lat": 0
}

### View a report
GET http://localhost:3000/reports/4
