// HTTP Request using REST client vscode extension
// Compose MULTIPLE requests in a single file (separated by ### delimiter)

### List Messages
GET http://localhost:3000/messages

### Create New Message
// Single line space below content type is mandatory
POST http://localhost:3000/messages
Content-Type: application/json

{
  "content": "prasan"
}

### Get Message with id
GET http://localhost:3000/messages/108
